export const Paths = {
    loginUrl: "/api/users/login",
    currentUserUrl: "/api/users/current",
    updateUserUrl: "/api/users/update",
    deleteUserUrl: "/api/users",
    registerUserUrl: "/api/users",
    logoutUrl: "/api/users/logout",
    getProductUrl: "/api/products",
    getSpecialsUrl: "/api/products/special",
    getAllProductsUrl: "/api/products",
    updateCartItemAmountUrl: "/api/cartitems/update",
    addCartItemUrl: "/api/cartitems",
    removeCartItemUrl: "/api/cartitems/remove",
    placeOrderUrl: "/api/products/order",
    getCartUrl: "/api/cartitems/user",
    deleteReviewUrl: "/api/reviews/review",
    deleteReplyUrl: "/api/reviews/reply",
    editReviewUrl: "/api/reviews/edit",
    addReviewUrl: "/api/reviews",
    subscribeUrl: "/api/users/subscribe",
    unsubscribeUrl: "/api/users/unsubscribe",
}